use crate::pipeline::traits::CompressedContext;

pub fn export_claude(context: &CompressedContext, project_name: &str) -> String {
    format!(
r#"# Project: {project_name}

{content}

## Notes
- This context was generated by ContextHub
- Compression level and file selection are optimized for Claude's context window
"#,
        project_name = project_name,
        content = context.content,
    )
}
