use crate::pipeline::traits::CompressedContext;

pub fn export_gemini(context: &CompressedContext, project_name: &str) -> String {
    format!(
r#"# {project_name} - Project Context

<!-- Generated by ContextHub for Gemini -->

{content}

---
*Context size: ~{token_count} tokens, {files_included} files included*
"#,
        project_name = project_name,
        content = context.content,
        token_count = context.token_count,
        files_included = context.files_included,
    )
}
