use crate::pipeline::traits::CompressedContext;

pub fn export_markdown(context: &CompressedContext, project_name: &str) -> String {
    format!(
r#"# {project_name} - Complete Project Context

> Generated by ContextHub
> Files included: {files_included}
> Estimated tokens: {token_count}

---

{content}
"#,
        project_name = project_name,
        content = context.content,
        token_count = context.token_count,
        files_included = context.files_included,
    )
}
