use crate::db::models::FileEntry;

const HIGH_SCORE_PATTERNS: &[&str] = &[
    "main.rs", "main.ts", "main.js", "main.py", "main.go",
    "mod.rs", "lib.rs",
    "index.ts", "index.js",
    "app.tsx", "app.jsx",
    "router.ts", "router.js",
    "config.ts", "config.js",
];

const MEDIUM_SCORE_PATTERNS: &[&str] = &[
    "test_", "_test.", ".spec.", ".test.",
    "README", "CHANGELOG",
];

const LOW_SCORE_PATTERNS: &[&str] = &[
    ".min.js", ".min.css", ".map",
    "generated", "autogenerated",
];

pub fn score_file(file: &FileEntry) -> f64 {
    let mut score: f64 = 0.5;

    let path_lower = file.path.to_lowercase();

    if HIGH_SCORE_PATTERNS.iter().any(|p| path_lower.contains(p)) {
        score += 0.3;
    }

    if MEDIUM_SCORE_PATTERNS.iter().any(|p| path_lower.contains(p)) {
        score += 0.1;
    }

    if LOW_SCORE_PATTERNS.iter().any(|p| path_lower.contains(p)) {
        score -= 0.3;
    }

    if let Some(ref lang) = file.language {
        match lang.as_str() {
            "Rust" | "TypeScript" | "JavaScript" | "Python" | "Go" => score += 0.15,
            "HTML" | "CSS" | "SCSS" => score += 0.05,
            "JSON" | "YAML" | "TOML" => score += 0.02,
            _ => {}
        }
    }

    if file.is_entry {
        score += 0.2;
    }

    if let Some(size) = file.size_bytes {
        if size > 100_000 {
            score -= 0.1;
        }
    }

    score.clamp(0.0, 1.0)
}

pub fn score_all_files(files: &[FileEntry]) -> Vec<(FileEntry, f64)> {
    files
        .iter()
        .map(|f| {
            let score = score_file(f);
            (f.clone(), score)
        })
        .collect()
}
